version = 0.1

[default.global.parameters]
stack_name = "clearsky-dev"
region = "ap-south-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Stage=dev DemoMode=true LlmProvider=openai LlmModelId=gpt-4o-mini WaMode=cloud SttProvider=transcribe TtsProvider=polly CorsOrigins=https://clearsky.akkki.tech"
